# -*- coding: utf-8 -*-

GUI_RPC_AUTH_CONFIG = "gui_rpc_auth.cfg"

RUN_MODE_ALWAYS = 0
RUN_MODE_NEVER  = 1
RUN_MODE_AUTO   = 2

RESULT_NEW               = 0
RESULT_FILES_DOWNLOADING = 1
RESULT_FILES_DOWNLOADED  = 2
RESULT_COMPUTE_ERROR     = 3
RESULT_FILES_UPLOADING   = 4
RESULT_FILES_UPLOADED    = 5

CPU_SCHED_UNINITIALIZED = 0
CPU_SCHED_PREEMPTED     = 1
CPU_SCHED_SCHEDULED     = 2

ERR_ABORTED_VIA_GUI = -197
